name: Docs (GitHub Pages)
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz
      - name: Build docs
        run: doxygen Doxyfile || true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install --with-deps chromium
      - name: Generate docs screenshot
        run: |
          python - <<'PY'
          from playwright.sync_api import sync_playwright
          from pathlib import Path
          html = Path('docs/html/index.html').resolve()
          out = Path('docs/html/screenshot.png')
          out.parent.mkdir(parents=True, exist_ok=True)
          with sync_playwright() as p:
              b = p.chromium.launch()
              pg = b.new_page(viewport={"width": 1280, "height": 800})
              pg.goto(html.as_uri(), wait_until="load")
              pg.screenshot(path=str(out))
              b.close()
          PY
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
