name: Release

on:
  push:
    tags:
      - 'v*.*.*'   # например v1.2.3
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: seanmiddleditch/gha-setup-ninja@v5

      # Linux/macOS компилятор по умолчанию ок
      - name: Configure (Release)
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_IPO=ON

      - name: Build
        run: cmake --build build -j

      - name: Install to staging
        run: cmake --install build --prefix "$PWD/stage"

      - name: Package (cpack)
        working-directory: build
        run: |
          cpack -G TGZ -B "$PWD/pack"
          cpack -G ZIP -B "$PWD/pack"
        # Итоговые файлы будут в build/pack/*.tar.gz и *.zip

      - name: List packages
        run: ls -lh build/pack || true

      - name: Upload packages as workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "packages-${{ runner.os }}"
          path: |
            build/pack/*.zip
            build/pack/*.tar.gz

  publish:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/**/*
          generate_release_notes: true